# Generated by Django 5.1.1 on 2024-09-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_model_tenant_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='file_path',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
