# Generated by Django 5.1.1 on 2024-09-27 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_model_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='file_name',
        ),
    ]
