# Generated by Django 5.1.1 on 2024-10-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_user_is_active_user_is_staff_user_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Tenant', 'Tenant')], max_length=20),
        ),
    ]
