# Generated by Django 5.1.1 on 2024-10-14 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_remove_rentalspaces_model_path_rentalspaceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='three_path',
            field=models.FileField(blank=True, null=True, upload_to='3Dfiles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['glb'])]),
        ),
        migrations.DeleteModel(
            name='RentalSpaceImage',
        ),
    ]
